import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import CourseMap from './CourseMap'
type GroupPin={id:number;user_id:number;created_at:string;name:string;note:string;lat:number;lng:number;color:string;nickname?:string;avatar?:string}
type GroupMap={id:number;title:string;description:string;price:number;invite_code:string;member_count:number;joined:boolean;leader:{nickname:string;avatar:string};pins:GroupPin[]}
const colors=['#c9343d','#e0474c','#77777c','#d98a22','#2c917b']
const json=(r:Response)=>r.ok?r.json():r.json().then(x=>Promise.reject(new Error(x.detail||'잠시 후 다시 시도해 주세요.')))
export default function GroupMaps({userId}:{userId:number}){
 const [maps,setMaps]=useState<GroupMap[]>([]),[selected,setSelected]=useState<GroupMap|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[code,setCode]=useState(''),[draft,setDraft]=useState<{lat:number;lng:number}|null>(null),[pinName,setPinName]=useState(''),[note,setNote]=useState(''),[color,setColor]=useState(colors[0]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const data=await api('group-maps?user_id='+userId).then(json);setMaps(data);if(selected){const fresh=data.find((x:GroupMap)=>x.id===selected.id);setSelected(fresh||null)}}catch(e){setMessage(e instanceof Error?e.message:'모임 지도를 불러오지 못했어요.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const create=async()=>{if(!title.trim()){setMessage('모임 지도 이름을 입력해 주세요.');return}try{const map=await api('group-maps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,user_id:userId})}).then(json);setMaps(x=>[map,...x]);setSelected(map);setTitle('');setDescription('');setMessage('모임 지도를 만들었어요. 초대 코드를 팀원에게 전달해 주세요.')}catch(e){setMessage(e instanceof Error?e.message:'모임 지도를 만들지 못했어요.')}}
 const join=async()=>{if(!code.trim())return;try{const map=await api('group-maps/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invite_code:code,user_id:userId})}).then(json);setMaps(x=>x.some(m=>m.id===map.id)?x.map(m=>m.id===map.id?map:m):[map,...x]);setSelected(map);setCode('');setMessage('모임 지도에 참여했어요. 이제 함께 핀을 남길 수 있어요.')}catch(e){setMessage(e instanceof Error?e.message:'참여하지 못했어요.')}}
 const addPin=async()=>{if(!selected||!draft||!pinName.trim())return;try{await api(`group-maps/${selected.id}/pins`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:pinName,note,lat:draft.lat,lng:draft.lng,color,user_id:userId})}).then(json);setDraft(null);setPinName('');setNote('');setMessage('모임 지도에 핀을 추가했어요.');await load()}catch(e){setMessage(e instanceof Error?e.message:'핀을 남기지 못했어요.')}}
 if(selected) return <section className="group-workspace"><div className="group-map-area"><CourseMap pins={selected.pins} onPick={(lat,lng)=>{setDraft({lat,lng});setPinName('');setNote('')}}/><button className="round-back" onClick={()=>setSelected(null)}>←</button><div className="group-map-label"><span>모임 지도 · 990원</span><b>{selected.title}</b><small>{selected.member_count}/10명 참여 · 팀장 {selected.leader.nickname}</small></div>{draft&&<div className="group-pin-form"><b>함께 볼 장소 핀</b><input autoFocus value={pinName} onChange={e=>setPinName(e.target.value)} placeholder="장소 이름"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="팀원에게 남길 한마디"/><div className="group-colors">{colors.map(c=><button key={c} aria-label="핀 색상" style={{background:c}} className={color===c?'chosen':''} onClick={()=>setColor(c)}/>)}</div><div><button onClick={()=>setDraft(null)}>취소</button><button onClick={addPin}>핀 남기기</button></div></div>}</div><div className="group-detail"><span className="tag">팀원 공유용</span><h1>{selected.title}</h1><p>{selected.description||'함께 가고 싶은 장소를 모아 보세요.'}</p><div className="invite-card"><span>팀원 초대 코드</span><b>{selected.invite_code}</b><small>팀원은 이 코드를 입력해 참여할 수 있어요. 최대 10명까지 참여 가능합니다.</small></div><h2>함께 남긴 핀 {selected.pins.length}개</h2>{selected.pins.length?<div className="group-pin-list">{selected.pins.map(pin=><article key={pin.id}><i style={{background:pin.color}}/> <div><b>{pin.name}</b><small>{pin.nickname||'팀원'} · {pin.note||'남긴 메모가 없어요.'}</small></div></article>)}</div>:<div className="empty">지도를 눌러 첫 번째 모임 핀을 남겨 보세요.</div>}</div></section>
 return <section className="content groups-page"><div className="heading"><span>모임 지도</span><h1>함께 떠날 곳을<br/>한 장의 지도로</h1><p>팀장이 만든 모임 지도에 초대 코드로 참여하고, 모두가 볼 수 있는 핀을 남겨 보세요.</p></div><section className="group-action-card"><h2>새 모임 지도 만들기 <em>990원</em></h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 제주도 졸업여행"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="함께 만드는 지도 소개 (선택)"/><button className="purchase" onClick={create}>팀장으로 모임 지도 만들기</button></section><section className="join-card"><b>초대 코드가 있나요?</b><div><input value={code} onChange={e=>setCode(e.target.value)} placeholder="예: PIN123456"/><button onClick={join}>참여하기</button></div><small>한 지도에는 최대 10명까지 참여할 수 있어요.</small></section><h2>내 모임 지도</h2>{loading?<div className="empty">모임 지도를 불러오고 있어요.</div>:maps.length?<div className="group-list">{maps.map(map=><button key={map.id} onClick={()=>setSelected(map)}><span>{map.leader.avatar}</span><div><b>{map.title}</b><small>{map.member_count}/10명 · 핀 {map.pins.length}개 · 팀장 {map.leader.nickname}</small></div><em>열기 →</em></button>)}</div>:<div className="empty">아직 참여한 모임 지도가 없어요.<br/>팀장이 되어 만들거나 초대 코드로 참여해 보세요.</div>}{message&&<p className="group-message">{message}</p>}</section>
}
